# Generated by Django 3.2.16 on 2024-12-07 12:57

from django.db import migrations

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_myuser_bio'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', users.models.MyUserManager()),
            ],
        ),
    ]
